### ISSUE TITLE
forge.sh is not using mono on linux

### ISSUE THREAD

**Issue by space-santa** [fsharp-editing/Forge#105]
After I followed the manual installation instructions for linux, I tried to run `forge` to create a new project.
I got this:
```
src/Forge/temp/Forge.exe: cannot execute binary file: Exec format error
```

## Expected Behavior
I would expect forge to just work. Is there a reason that `forge.sh` is not using `mono` when executing `Forge.exe`?

## Current Behavior
The current `forge.sh` script is not using `mono` when executing `Forge.exe`

## Possible Solution
```
diff --git a/forge.sh b/forge.sh              
index d98ace5..c9863d0 100644                 
--- a/forge.sh         
+++ b/forge.sh         
@@ -2,4 +2,4 @@        
 # User just ran a symbolic link which points to real Forge.exe                              
 # $0 is an absolute path of this symboliklink                                               
 # $* stands for all arguments passed to the command                                         
-"$(dirname $(readlink $0))/Forge.exe" $*     
+mono "$(dirname $(readlink $0))/Forge.exe" $* 
```

## Steps to Reproduce (for bugs)
1. Follow the manual installation instructions. (git clone and .build.sh)
2. Symlink forge.sh into the $PATH
3. Run forge
4. Get error

## Context
This issue didn't affect me too much, I just added mono to forge.sh. It would still be nice to not having to do that.

## Your Environment
```
$mono --version
Mono JIT compiler version 5.8.0.127 (tarball Wed Feb 21 04:20:57 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```
```
$ fsharpc
Microsoft (R) F# Compiler version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.
```
Running on Fedora27 x64

**Comment by Krzysztof-Cieslak** [comment]
Yeah, it's a bug. Please send a PR.

**Comment by space-santa** [comment]
Done :-)
