### ISSUE TITLE
Wrong `TargetFramework` version in project file

### ISSUE THREAD

**Issue by mclang** [fsharp-editing/Forge#111]
When creating new F# FAKE console application with Forge, the `TargetFramework` of the generated project file is wrong.

## Expected Behavior
According to the .NET Framework FAKE downloads, the value in project file should be:
`<TargetFramework>netcoreapp2.0</TargetFramework>`

## Current Behavior
The project file tries to use older framework version:
`<TargetFramework>net461</TargetFramework>`

After changing the value, running `./build.sh` succeeds.

## Your Environment
* Solus Linux with Mono 5.4.1.6
* CentOS 7.4 with 5.10.1.20
* Forge 2.2.0

**Comment by mclang** [comment]
Hmm... I read some tutorials like this:
https://atlemann.github.io/fsharp/2018/02/28/fsharp-solutions-from-scratch.html

and found out that `<TargetFramework>net461</TargetFramework>` might be right after all if NOT targeting to dotnet core. Problem is, how to get FAKE build succeed with that?

How to use normal system Mono with current Forge and FAKE?

**Comment by Krzysztof-Cieslak** [comment]
Targeting `net461` by default is by-design. Unfortunately, for targeting `mono` on Linux and compiling with `dotnet build` (what our FAKE build script does) one requires workaround described in https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0.1#using-net-framework-as-targets-framework-the-osxunix-build-fails.
