### ISSUE TITLE
vscode integration?

### ISSUE THREAD

**Issue by alexgman** [fsharp-editing/Forge#116]
How do we integrate this into vscode? Are there any other tools available for vscode specifically for F# formatting?

**Comment by Jarak-Jakar** [comment]
If I'm not mistaken, Forge is already integrated into the Ionide extension for VS Code (which is a really good extension, I definitely recommend it).

Last I knew, there wasn't really a current auto-formatter for F# (more's the pity), but I certainly don't claim to be up-to-date on such matters.
