### ISSUE TITLE
Allow multiple files to be added at once

### ISSUE THREAD

**Issue by TomMD** [fsharp-editing/Forge#144]
It should be possible to add multiple files:

```
forge file add *.fs
```

Currently this results in an error:

```
% forge new --name foo --dir src --template console
% cd src/foo
% ls
App.config foo.fs     foo.fsproj
% touch x.fs
% touch y.fs
% forge file add {x,y}.fs
unrecognized argument: 'y.fs'.
```

**Comment by Krzysztof-Cieslak** [comment]
I don't think it's a feature I'd like to see. Globing (*.fs) would be problematic from ordering point of view (files in F# projects need to be ordered). And I don't think that adding multiple files at once is common enough usecase.
