### ISSUE TITLE
Unable to add project to empty solution

### ISSUE THREAD

**Issue by JeremyBellows** [fsharp-editing/Forge#165]
When the command `add project` is executed, Forge exits without any prompt or action. 

Tried on Windows and Linux
## Steps to Recreate issue
1. Open Forge menu using `forge`
2. Create empty solution using `new project` 
3. Select 'sln' for template
4. On the Forge menu, execute `add project`

**Comment by Krzysztof-Cieslak** [comment]
`add project` adds project to project references, not adding projects to `sln` file,

**Comment by JeremyBellows** [comment]
Ah that explains that. It may be worth adding further explanation on the commands and usage in the documentation to clarify this and clear any confusion.
