### ISSUE TITLE
forge update -h causes error

### ISSUE THREAD

**Issue by selketjah** [fsharp-editing/Forge#28]
## Expected Behavior

According to the help: update: <paket|fake> Updates Paket or FAKE

typing 'forge update -h' should show the options 'Fake' and 'Paket'
typing 'forge update fake' should update Fake
typing 'forge update paket' should update Paket

## Current Behavior

![image](https://cloud.githubusercontent.com/assets/2250570/21425286/89b837d8-c848-11e6-938e-64169a67b098.png)

## Your Environment

* Version used: 1.3.1
* Operating System and version: Windows 10

**Comment by selketjah** [comment]
There is a conflict with the default aliases for this:
argument "update" is an alias for "paket update", so paket tries to execute the command like this:
"paket update -h", which gives the error above.
Same applies for the other two commands that give the error

**Comment by Krzysztof-Cieslak** [comment]
Yes, we need `update` command - I think having command to update FAKE, and especially Paket is important. 

At the same time I like `update` alias, it's probably one of the command I use most often.

Maybe we should replace `update` with `update-version` or something like that?

**Comment by selketjah** [comment]
I have given this a lot of thought and this is what I would do:

at this point in time, you can do a "_paket update_" but not a "_fake update_"
_update_ is an alias for "_paket update_" command.

I would implement the "update" for Fake, so people could do "_fake update_"
and remove the "_update_" command from the main commands 

this way, no functionality is lost and it makes the domain more consistent.

let me know what you think

**Comment by Krzysztof-Cieslak** [comment]
I've changed `update` command (updating internal Forge's Paket or FAKE installation) into `update-version` which better describes its usage.

Now `forge update` is alias for `forge paket update` (running paket with parameter update) and error is valid - Paket doesn't support short syntax for help (only `--help`)
