### ISSUE TITLE
`forge refresh` exists with 1

### ISSUE THREAD

**Issue by haf** [fsharp-editing/Forge#34]
<img width="497" alt="screen shot 2017-01-03 at 13 47 02" src="https://cloud.githubusercontent.com/assets/193115/21608156/274b8b0a-d1bb-11e6-8edc-6283cafdfb91.png">

## Expected Behavior

Exit w/ 0

## Env:

OS X 10.11.8, homebrew with no updates pending. Mono 4.6.2.

**Comment by Krzysztof-Cieslak** [comment]
Does it refresh templates? Or just silently crash doing nothing?

**Comment by haf** [comment]
It refreshes them.

**Comment by Krzysztof-Cieslak** [comment]
Fixed as a part of #71
