### ISSUE TITLE
Non-executable `build.sh` generated

### ISSUE THREAD

**Issue by haf** [fsharp-editing/Forge#35]
When running `forge new project --name Api --folder ./Api --template suave`, a file called `build.sh` is created, but its flags don't include the executable bit. It should, because it should be possible to build directly after creating the project without knowing how to use `chmod` on Unix systems.

**Comment by Krzysztof-Cieslak** [comment]
I don't know a lot about *nix OSes but shouldn't https://github.com/fsharp-editing/Forge/blob/master/src/Forge.Core/Templates.fs#L196-L197 be enough?

**Comment by haf** [comment]
Even if it is `File.WriteAllText` recreates the file [here](https://github.com/fsharp-editing/Forge/blob/master/src/Forge.Core/Templates.fs#L200).

**Comment by Krzysztof-Cieslak** [comment]
:facepalm:

**Comment by haf** [comment]
🤦
