### ISSUE TITLE
How to add project to solution file?

### ISSUE THREAD

**Issue by diegobfernandez** [fsharp-editing/Forge#46]
I have an existing project that is not listed on .sln file.
I searched for something like `forge add project -n src/MyProject/MyProject.fsproj -s MySolution.sln` but could not find a way to do it.

**Comment by juselius** [comment]
You should be able to do that using `forge add file -s MySolution.sln -n src/MyProject/MyProject.fsproj` (note that -s must come before -n). However when I try that, forge aborts silently with exit code 1. I'm using NixOS, so it might have something to do with that.

**Comment by Krzysztof-Cieslak** [comment]
I don't think editing solution files is implemented.

**Comment by juselius** [comment]
Ok. What is the best way to add projects to the pristine sln file (created by `forge new solution -n MySolution`)? Just edit it by hand?

**Comment by Krzysztof-Cieslak** [comment]
I know nothing about solution files, I'm not using them. Sorry.

**Comment by juselius** [comment]
👍 

@cloudRoutine has started implementing soulution file handling in Forge.Core/SolutionSystem.fs, but it seems it's not quite finished yet.

**Comment by mateuszlewko** [comment]
Any updates on this issue? Is it now possible to add project to the solution file?

**Comment by ryukinix** [comment]
Really wishful feature. On the end I need to use a IDE to add it (unfortunately)

**Comment by enricosada** [comment]
as a note, if you have .net core sdk isntalled, you can do:

`dotnet sln my.sln add path/to/my.fsproj`

or just `dotnet sln add path/to/my.fsproj` if there is only one sln.

So maybe can be closed?

**Comment by mateuszlewko** [comment]
Yeah, it's fine with me.
