### ISSUE TITLE
New project target incompatible with mono

### ISSUE THREAD

**Issue by bbrik** [fsharp-editing/Forge#55]
When I use "forge new project", then generated project targets .Net v4.6.2.
I get compiler warnings that it is incompatible with mono.

`warning : TargetFrameworkVersion 'v4.6.2' not supported by this toolset (ToolsVersion: 14.0)
`
If I change the target to v4.5, I stop getting the warnings.
I am working on El Capitan, mono is v4.8.0, forge v1.3.3

**Comment by henrytill** [comment]
Similar problem here.  OS X 10.11.6, Mono 4.8.0, Forge 1.4.1.

**Repro**:
```
mkdir testproj
cd testproj
forge new project --name testproj --dir . --template console
...
./build.sh
```

The build will fail with the following error: 
```
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1127,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

If I manually change `TargetFrameworkVersion` in `testproj/testproj.fsproj` to `v4.5`, the build will succeed.

**Comment by Krzysztof-Cieslak** [comment]
I believe `4.6.2` should be supported in latest mono version.
