### ISSUE TITLE
`forge rename file` deletes unrelated parts of the project file 

### ISSUE THREAD

**Issue by Gastove** [fsharp-editing/Forge#62]
## Expected Behavior
`forge rename file` should rename the specified file on disk and in the `fsproj` file, but should not otherwise modify the `fsproj` in question.

## Current Behavior
`forge rename file` renames the file on disk and in the `fsproj` file, but after, an `ItemGroup` has been removed and the project no longer compiles.

Vis:

```
rossdonaldson@becon λ ~/Code/personal/gearheart on master[!]
$ git status
On branch master
nothing to commit, working tree clean

rossdonaldson@becon λ ~/Code/personal/gearheart on master
$ forge rename file -p src/machinist/machinist.fsproj -n src/machinist/machinist.fs -r src/machinist/Machinist.fs
seq ["Samples.fs"; "Phabricator.fs"; "Database.fs"; "Args.fs"; ...]

rossdonaldson@becon λ ~/Code/personal/gearheart on master[!]
$ git diff src/machinist/machinist.fsproj
diff --git a/src/machinist/machinist.fsproj b/src/machinist/machinist.fsproj
index 1fdff15..383df1d 100644
--- a/src/machinist/machinist.fsproj
+++ b/src/machinist/machinist.fsproj
@@ -43,7 +43,7 @@
     <Compile Include="Phabricator.fs" />
     <Compile Include="Database.fs" />
     <Compile Include="Args.fs" />
-    <Compile Include="machinist.fs" />
+    <Compile Include="Machinist.fs" />
     <None Include="App.config" />
   </ItemGroup>
   <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
@@ -262,13 +262,6 @@
       </ItemGroup>
     </When>
   </Choose>
-  <ItemGroup>
-    <Reference Include="FSharp.Data.SqlProvider">
-      <HintPath>..\..\packages\SQLProvider\lib\FSharp.Data.SqlProvider.dll</HintPath>
-      <Private>True</Private>
-      <Paket>True</Paket>
-    </Reference>
-  </ItemGroup>
   <Choose>
     <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And $(TargetFrameworkVersion) == 'v4.6.3'">
       <ItemGroup>
```

Unfortunately I rather need that SqlProvider :P. 

## Possible Solution
Seems like a straight-up "it shouldn't do that", but I'm new to the language and tooling -- possibly I'm doing something wrong? 

## Steps to Reproduce (for bugs)
Pretty much as it says above -- have a project with a SqlProvider item group, change the name of a file in that project. 

## Your Environment
* Version used: 1.3.3 (Note: there doesn't seem to be a way to get forge to admits its version. Am I wrong?) 
* Environment name and version (F#, .Net): mono 4.8.0, F# 4.1
* Operating System and version: macOS Sierra

**Comment by Tarmil** [comment]
This `ItemGroup` itself is a bit strange. It has `<Paket>True</Paket>`, which suggests that it has been generated by Paket, but if that's the case then it should be inside a `<Choose>` element. And indeed I do get it in a `<Choose>` element when I do the following:

```
forge new project -n Test --dir . -t console
forge paket add nuget SqlProvider project Test
```

I can reproduce your issue if I edit the fsproj by hand to move the `<ItemGroup>` out of its `<Choose>` element. But as far as I can tell that's an invalid state. You can restore the file to a valid state by running:

```
forge paket install
```
