### ISSUE TITLE
Moving Forge to new brave world

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fsharp-editing/Forge#70]
I think it's high time to create Forge 2.0 that will move Forge templates to, and adds support for new fsproj files.

Actually I believe that changes in specification were pretty minimal, the only problem is that lot of things that were optional in specification are also now optional in reality (and we don't handle it because we had to follow VS requirements, not specification).

CC: @enricosada for more info about new fsprojs

**Comment by skalinets** [comment]
I noticed that adding file to the project is [broken](http://i.imgur.com/zFEQTK3.png). Is it because of the new `fsproj` format?

**Comment by Krzysztof-Cieslak** [comment]
Ionide is still using 1.X version of Forge which doesn't support new fsproj.

2.0 that moves everything to new `fsproj` is in preview - https://github.com/fsharp-editing/Forge/pull/71
