### ISSUE TITLE
Feature Request: "Generate References" ala F# power tools

### ISSUE THREAD

**Issue by onionhammer** [fsharp-editing/Forge#75]
It would be great if Forge could automatically generate references from an fsproj as a script, the same way F# power tools does for Visual Studio

**Comment by Krzysztof-Cieslak** [comment]
I don't believe we are able to accurately generate references with our current parsing of `fsproj` files. I believe this feature is much easier to be done for tools using FSharp.Compiler.Service (and using its ProjectCracker). [For example we've added this feature to Ionide]
