### ISSUE TITLE
How to add a asset file to a project?

### ISSUE THREAD

**Issue by ryukinix** [fsharp-editing/Forge#75]
I wants add a `data/Template.json` to my project `data/data.fsproj`. But when I try to execute from solution root:

`forge add file -p data/data.fsproj -n data/Template.json`

I got compile error because Template.json is added with tag `Compile`. There is some way to add a non-compiling file to a project? (I mean, like a `Template.json`, which obviously is not a file to compile).

Like this:

```xml
  <Content Include="Template.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
```

Instead 
```xml
<Compile Include="Template.json/>
```

**Comment by Krzysztof-Cieslak** [comment]
Using `--build-action Content`  should set `Content` instead of `Compile`. Unfortunately, there is no way to add `CopyToOutputDirectory` with Forge at the moment

**Comment by ryukinix** [comment]
Thanks for the fast answer, @Krzysztof-Cieslak!  
Should I close this issue or this can be a feature to be implemented on future?
