### ISSUE TITLE
Single command for specific project/-type

### ISSUE THREAD

**Issue by haf** [fsharp-editing/Forge#76]
What's the command to do

```
$ forge new project
suave
```

as a single command line?

The reason for asking is that the normal `forge new --help` nor `forge new project --help` gives docs on how to call it with a specified sort of project, and `forge new project suave` or `forge new project type suave` all fail to work.

So this issue can either be to

 a) Document is with `--help`
 b) document how to do it in the README, which is the second place I go
 c) Support the 'guessed' variants.

**Comment by Krzysztof-Cieslak** [comment]
`forge new project -n SampleProj --folder src -t suave` should work.
The syntax for all commands is described in the wiki - https://github.com/fsharp-editing/Forge/wiki/new-project. And readme links to the wiki in the second sentence ;)

Also `forge new project --help` should print all additional parameters that can be used ... or at least it prints it on current master:
![image](https://user-images.githubusercontent.com/5427083/29752786-94e89d98-8b64-11e7-9c2a-c771ecb13964.png)
