### ISSUE TITLE
Console template does not work with F#4.1 if Visual Studio is not installed

### ISSUE THREAD

**Issue by ChrSteinert** [fsharp-editing/Forge#78]
On a fresh install of Windows with F#4.1 the console template, that I use with Ionide, seems to not support F#4.1 when no Visual Studio is installed.
Creating a new project with Ionide "F#: New Project" and the `console` template works. But building it fails.

## Expected Behavior
Build works

## Current Behavior
Build fails with:

```
Fehler beim Buildvorgang.

       "C:\Users\chrst\Desktop\test2\Test2\Test2.fsproj" (Build Ziel) (1) ->
         C:\Users\chrst\Desktop\test2\Test2\Test2.fsproj : error MSB4057: Das Ziel "Build" ist im Projekt nicht vorhanden.

    0 Warnung(en)
    1 Fehler
```
(says `Target "Build" is missing` in German)

## Possible Solution

The problem seems to be that the `Microsoft.FSharp.Targets` cannot be found.
In the fsproj file in the section where the `FSharpTargetsPath` is set I added basically the following:
```
<Otherwise>
  <PropertyGroup>
    <FSharpTargetsPath>$(FSHARPINSTALLDIR)\Microsoft.FSharp.Targets</FSharpTargetsPath>
  </PropertyGroup>
</Otherwise>
```
With this, the targets file can be found and the build succeeds.

## Steps to Reproduce (for bugs)
On a fresh Windows 10 install:
1. Install MSBuild 15
2. Install F#4.1 (Step 4 of Option 4 on http://fsharp.org/use/windows/)
3. Install VS Code with Ionide
4. Execute Command "F#: New Project" - with the console template
5. After everything is ready, execute `build.cmd` in the projects root folder.

## Your Environment

Version used:
* Windows 10 
* F# 4.1 
* .NET 4.6.2

What got me wondering; what is this line all about:
`<MinimumVisualStudioVersion Condition="'$(MinimumVisualStudioVersion)' == ''">14</MinimumVisualStudioVersion>`
It does not seem to have any influence in this setup.

I'll be happy to provide a fix for the template if this is wanted.

**Comment by Krzysztof-Cieslak** [comment]
I think this won't be an issue any more in Forge 2.0 (current master) as we're moving to SDK based project templates.

**Comment by ChrSteinert** [comment]
Let's wait for this then.   :)
