### ISSUE TITLE
Suave-Fable scaffold?

### ISSUE THREAD

**Issue by haf** [fsharp-editing/Forge#80]
Continuing from 'suave-` as a prefix.

**Comment by haf** [comment]
What's needed to make this a template?

https://github.com/fsharp-editing/Forge/wiki/How-to-contribute-to-Forge doesn't talk about adaptation for creating them.

Should we make the server equal the app name?

Ping @alfonsogarciacaro @Krzysztof-Cieslak @ademar

**Comment by Krzysztof-Cieslak** [comment]
It's bit more complex than rest of the templates since Forge was designed to work on "project" level while this scaffold is multi project temple with specific "solution" level files. 

We don't yet support such scenario but it's definitely on my road map... for multiple reasons ;)
