### ISSUE TITLE
Improve product positioning

### ISSUE THREAD

**Issue by pkese** [fsharp-editing/Forge#88]
Reading the Forge landing page, it is clear what forge does:

     Forge is a command line tool that provides tasks for creating and managing F# projects.

It is unclear why I'd use it.

The above sentence should continue with:

    , unlike the 'dotnet' cli, Forge _______________

to make that clear.

**Comment by Krzysztof-Cieslak** [comment]
I don't think I want to compare with `dotnet` CLI. Also http:\\forge.run, and Wiki in the repo contains quite nice overview of the features.
